name: Cloud Orchestrator Recipe
description: 'Cloud Orchestrator recipe'
type: Administration
install:
  - anonymous_redirect
  - admin_toolbar
  - admin_toolbar_tools
  - aws_cloud
  - cloud_dashboard
  - copyright_footer
  - ctools
  - geocoder
  - k8s
  - login_destination
  - module_filter
  - module_permissions
  - module_permissions_ui
  - openid_connect_daccount
  - openstack
  - password_policy
  - password_policy_character_types
  - password_policy_length
  - real_aes
  - roleassign
  - terraform
  - tfa
  - vmware
  - bootstrap_cloud
  - bootstrap5
  - rigel
config:
  # Set to false for now.
  strict: false
  import:
    cloud: '*'
    aws_cloud: '*'
    k8s: '*'
    vmware: '*'
    terraform: '*'
    openstack: '*'
  actions:
    system.site:
      simpleConfigUpdate:
        page.front: '/clouds/tabbed-dashboard'
    system.theme:
      simpleConfigUpdate:
        default: 'rigel'
    aws_cloud.settings:
      simpleConfigUpdate:
        aws_cloud_instance_type_prices_spreadsheet: false
